// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUFttP9WnCgQ1w79K9wDB3RrLAGOSEIP0',
    appId: '1:92763907457:web:7becd7d9f30d695b06b480',
    messagingSenderId: '92763907457',
    projectId: 'zoom-clone-f7fbc',
    authDomain: 'zoom-clone-f7fbc.firebaseapp.com',
    storageBucket: 'zoom-clone-f7fbc.firebasestorage.app',
    measurementId: 'G-HGR4CMZHRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLcZvxzL1I89mzw8sAhLszAlNWm863rhY',
    appId: '1:92763907457:android:edc253194d74eb0b06b480',
    messagingSenderId: '92763907457',
    projectId: 'zoom-clone-f7fbc',
    storageBucket: 'zoom-clone-f7fbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTIZdHJR5gKZFiKHDs3ChzlSvoB7PRkrY',
    appId: '1:92763907457:ios:30ae20f578d519b606b480',
    messagingSenderId: '92763907457',
    projectId: 'zoom-clone-f7fbc',
    storageBucket: 'zoom-clone-f7fbc.firebasestorage.app',
    iosClientId: '92763907457-tka8d73k16octjg3gasonfpj1rjubd08.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTIZdHJR5gKZFiKHDs3ChzlSvoB7PRkrY',
    appId: '1:92763907457:ios:30ae20f578d519b606b480',
    messagingSenderId: '92763907457',
    projectId: 'zoom-clone-f7fbc',
    storageBucket: 'zoom-clone-f7fbc.firebasestorage.app',
    iosClientId: '92763907457-tka8d73k16octjg3gasonfpj1rjubd08.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUFttP9WnCgQ1w79K9wDB3RrLAGOSEIP0',
    appId: '1:92763907457:web:fca0ae19e83a7b3606b480',
    messagingSenderId: '92763907457',
    projectId: 'zoom-clone-f7fbc',
    authDomain: 'zoom-clone-f7fbc.firebaseapp.com',
    storageBucket: 'zoom-clone-f7fbc.firebasestorage.app',
    measurementId: 'G-33ZHTLJ1KM',
  );
}
